# Generated by Django 4.0.4 on 2022-05-16 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название блюда')),
                ('description', models.CharField(max_length=50, verbose_name='Описание блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Список Блюд',
            },
        ),
        migrations.CreateModel(
            name='DishType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.CharField(max_length=50, verbose_name='Тип блюда')),
            ],
            options={
                'verbose_name': 'Тип блюда',
                'verbose_name_plural': 'Типы блюд',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(max_length=50, verbose_name='Размер порции')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('dish', models.ManyToManyField(to='app.dish', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Список меню',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес')),
                ('manager_name', models.CharField(max_length=50, verbose_name='Имя менеджера')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Список ресторанов',
            },
        ),
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название Сети')),
                ('customer_satisfaction_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Оценка клиентов')),
                ('owners_name', models.CharField(max_length=50, verbose_name='Имя владельца')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.menu', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Сеть ресторанов',
                'verbose_name_plural': 'Сети ресторанов',
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.restaurantchain', verbose_name='Сеть ресторанов'),
        ),
        migrations.AddField(
            model_name='dish',
            name='dish_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dishtype', verbose_name='Тип блюда'),
        ),
    ]
