# Generated by Django 4.0.4 on 2022-05-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dish_dishtype_menu_restaurant_restaurantchain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishtype',
            old_name='dish_type',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='restaurantchain',
            name='menu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.menu', verbose_name='Меню'),
        ),
    ]
