# Generated by Django 4.0.4 on 2022-05-20 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_dish_type_dishtype_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название ингредиента')),
            ],
            options={
                'verbose_name': 'Ингредиенты',
                'verbose_name_plural': 'Ингредиент',
            },
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название блюда'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.AddField(
            model_name='menu',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.dish', verbose_name='Блюдо'),
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_list',
            field=models.ManyToManyField(null=True, to='app.ingredient', verbose_name='Список ингредиентов'),
        ),
    ]
