# Generated by Django 4.0.4 on 2022-05-20 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ingredient_alter_dish_description_alter_dish_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(verbose_name='Описание блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredient_list',
            field=models.ManyToManyField(to='app.ingredient', verbose_name='Список ингредиентов'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название блюда'),
        ),
    ]
