# Generated by Django 4.0.4 on 2022-05-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ingredient_options_alter_menu_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание блюда'),
        ),
    ]
