# Generated by Django 4.0.4 on 2022-05-21 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_restaurant_manager_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Номер телефона',
                'verbose_name_plural': 'Номера телефонов',
            },
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.phonenumber', verbose_name='Номер телефона'),
        ),
    ]
