# Generated by Django 4.0.4 on 2022-05-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_menuitem_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restaurant_chain',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantChain', to='app.restaurantchain', verbose_name='Название сети'),
            preserve_default=False,
        ),
    ]
