# Generated by Django 4.0.4 on 2022-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_menu_restaurant_chain_menu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
    ]
